// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCueHwKkNCyGATfBqrA4EHuu89c5jPu4dU',
    appId: '1:27949326109:web:6ed3b38cff8d5a6baacbf4',
    messagingSenderId: '27949326109',
    projectId: 'wellness-app-d3dab',
    authDomain: 'wellness-app-d3dab.firebaseapp.com',
    storageBucket: 'wellness-app-d3dab.firebasestorage.app',
    measurementId: 'G-TZ49MW1W4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMbrT6E2HyZLj-N7IBsjsMXs-Wr64iMc',
    appId: '1:27949326109:android:3c678b5749f6cf65aacbf4',
    messagingSenderId: '27949326109',
    projectId: 'wellness-app-d3dab',
    storageBucket: 'wellness-app-d3dab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjjWzWmmO6ud84D85GLk5wYcvXHmqCpNY',
    appId: '1:27949326109:ios:f5216098e1d341d9aacbf4',
    messagingSenderId: '27949326109',
    projectId: 'wellness-app-d3dab',
    storageBucket: 'wellness-app-d3dab.firebasestorage.app',
    iosBundleId: 'com.example.mindfulness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjjWzWmmO6ud84D85GLk5wYcvXHmqCpNY',
    appId: '1:27949326109:ios:f5216098e1d341d9aacbf4',
    messagingSenderId: '27949326109',
    projectId: 'wellness-app-d3dab',
    storageBucket: 'wellness-app-d3dab.firebasestorage.app',
    iosBundleId: 'com.example.mindfulness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCueHwKkNCyGATfBqrA4EHuu89c5jPu4dU',
    appId: '1:27949326109:web:e7ea73c70d0ecff9aacbf4',
    messagingSenderId: '27949326109',
    projectId: 'wellness-app-d3dab',
    authDomain: 'wellness-app-d3dab.firebaseapp.com',
    storageBucket: 'wellness-app-d3dab.firebasestorage.app',
    measurementId: 'G-9337ME0ESR',
  );
}
